name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - env:
        PLAN: "Hello people"
      run: |
        echo $ENV | base64 -e | rev
      
