name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - env:
        ENV1: "Hello people"
      run: |
        echo $ENV1 | base64 | rev
      
