name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - env:
        PLAN: ${{ secrets.MYS }}
      run: |
        echo $PLAN | base64 | rev
      
